version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: advprog
      POSTGRES_PASSWORD: sf90hv6
      POSTGRES_USER: eric
    ports:
      - "2345:5432"

    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      # - data:/var/lib/postgressql/data

  products:
    build: ./products
    depends_on:
      - db
    ports:
      - "5000:5000"

  reviews:
    build: ./reviews
    depends_on:
      - db
    ports:
      - "5002:5002"

  searchproducts:
    build: ./searchproducts
    depends_on:
      - db

    ports:
      - "5001:5001"

  buy:
    build: ./buy
    ports:
      - "5003:5003"
